# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=500)),
                ('line_formatted', models.CharField(max_length=500)),
                ('index', models.IntegerField()),
                ('duration', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='subs.Episode')),
            ],
        ),
    ]
